name: Workflow Demo

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
        
  download: #added
    concurrency: 
      group: production-deployment
      cancel-in-progress: false
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: dump github contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: run sleep 
        run: sleep 6s
        timeout-minutes: 1
      - name: Download text file
        uses: actions/download-artifact@v2
        with:
          name: hello-artifact
          path: ./artifacts
      - name: Display content of the text file
        run: cat ./artifacts/hello.txt
