name: Workflow Demo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
  download: #added
    concurrency: 
      group: production-deployment
      cancel-in-progress: false
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: run sleep 
        run: sleep 600s
      - name: Download text file
        uses: actions/download-artifact@v2
        with:
          name: hello-artifact
          path: ./artifacts
      - name: Display content of the text file
        run: cat ./artifacts/hello.txt
