name: pull request merged

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '.github/workflows/artifact.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
        
  download: #added
    concurrency: 
      group: production-deployment
      cancel-in-progress: false
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
  
    steps:
      - name: dump github contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: run sleep 
        run: sleep 6s
        timeout-minutes: 1
      - name: Download text file
        uses: actions/download-artifact@v2
        with:
          name: hello-artifact
          path: ./artifacts
      - name: Display content of the text file
        run: cat ./artifacts/hello.txt
      - name: Dump matrix context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Check if merged
        id: check_merged
        run: echo "PR_MERGED=${{ github.event.pull_request.merged }}" >> $GITHUB_ENV
      - name: Notify on merge
        if: steps.check_merged.outputs.PR_MERGED == 'true'
        run: echo "Pull request was merged!"

        
