name: matrix example
on: 
  push:
    paths:
      - '.github/workflows/matrix.yml'

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        docker: 
          - "alpine"
          - "hello-world"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker version
        run: docker -v

      - name: Run Docker image on ${{ matrix.os }}
        run: docker run ${{ matrix.docker }}
